export const GET_FEEDBACKS = 'GET_FEEDBACKS'
export const GET_FEEDBACK = 'GET_FEEDBACK'
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK'
export const UPDATE_FEEDBACK = 'UPDATE_FEEDBACK'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SET_CATEGORY = 'SET_CATEGORY'
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'
export const SET_MENU_ITEM = 'SET_MENU_ITEM'
export const SET_MOBILE_SIDEBAR = 'SET_MOBILE_SIDEBAR'
export const LOGIN_USER = 'LOGIN_USER'
export const LOG_OUT= 'LOG_OUT'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAIL= 'REGISTER_FAIL'
export const GET_USER = 'GET_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'







